webtalk_init -webtalk_dir C:/Users/kenry/OneDrive - CSULB/2021 - 2022/Spring 2022/CECS 341/Lab 4/lab_4/lab_4.sim/sim_1/behav/xsim/xsim.dir/Datapath_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 17 23:06:08 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "19942753-f085-4fc7-a3d4-b55aebe92a3e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6705cd004e6f4541aa85be7d22c1f2f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor              " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3593 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "670 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10280_KB" -context "xsim\\usage"
webtalk_transmit -clientid 654186062 -regid "" -xml C:/Users/kenry/OneDrive - CSULB/2021 - 2022/Spring 2022/CECS 341/Lab 4/lab_4/lab_4.sim/sim_1/behav/xsim/xsim.dir/Datapath_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/kenry/OneDrive - CSULB/2021 - 2022/Spring 2022/CECS 341/Lab 4/lab_4/lab_4.sim/sim_1/behav/xsim/xsim.dir/Datapath_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/kenry/OneDrive - CSULB/2021 - 2022/Spring 2022/CECS 341/Lab 4/lab_4/lab_4.sim/sim_1/behav/xsim/xsim.dir/Datapath_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
